# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487663e12bacec222e9b6695c7a1a16d8891addde4558c4de80ccb75b330624973a8d130a04d1e26ae96519c366962f9ea08fa9c67506354c246d6d2df6618f5

test:
  secret_key_base: 0195da2152ecf2a0944db751554bac3b80d416e5895a6a1ae38b606d6f8fd0dc072bbf029e2375d1b2852b2d16f8039b2efee9ea77e332fb3c7af94f7586d17f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
